In [3]:
set1={1,1,3,5,7,9,9}
print(set1)

{1, 3, 5, 7, 9}


In [5]:
set1:set={1,1,3,3,5,8,7,9,10}
set1.add(11)
set1

{1, 3, 5, 7, 8, 9, 10, 11}

In [9]:
for value in set1:
    print(value)

1
3
5
7
8
9
10
11


In [11]:
import numpy as np
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
import numpy as np
array1=np.array(range(1,11))

In [14]:
#numpy 就是整個array在計算，先安裝pip install numpy
import numpy as np
array1:np.ndarray=np.array(range(1,11))
array1+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
#陣列運算
array1+10*50

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [16]:
display(np.arange(1.3,3.5,0.1))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [17]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [18]:
display(np.random.random())
display(np.random.randn(10))


0.05267779249737614

array([ 1.64007274,  0.87896425,  1.24625855, -1.90801029,  1.14109294,
       -0.43657785,  0.91644889,  0.72444819, -0.96089231, -0.36761861])

In [19]:
display(np.random.random())
display(np.random.randn(10,5))

0.37476875563460266

array([[ 8.96241748e-01,  4.22375010e-02,  7.59689461e-01,
         1.67621804e+00,  1.54253278e+00],
       [ 1.04609356e+00, -1.88218476e+00, -1.19038794e+00,
        -7.51905533e-01, -1.50506505e-01],
       [-4.79543654e-01, -5.04124323e-01, -7.46604968e-01,
         1.25719922e+00,  2.12880142e-03],
       [ 4.59275628e-02,  1.19793924e+00, -3.07756146e-01,
         1.08922938e+00,  2.24840282e-01],
       [-2.69833159e+00,  5.81702850e-01, -5.62243968e-02,
        -1.28832364e+00,  3.44584910e-01],
       [-3.83990746e-02,  2.50018035e-01,  6.25469925e-01,
         1.35960605e+00, -2.61832973e-01],
       [ 1.93868063e+00,  6.86386778e-01, -1.21155470e-01,
         5.15874370e-01, -4.20614030e-01],
       [-1.02034397e-01, -4.24659749e-01, -1.04518527e+00,
         6.92230929e-02,  1.41622298e-02],
       [ 9.70689353e-01,  1.64569695e-01,  6.33475788e-01,
         4.95974816e-01,  2.67571827e-01],
       [ 5.34899916e-01,  1.51131963e+00, -2.34450557e+00,
         2.56928044e+00

In [21]:
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10))

0.447739684805207

array([[[-0.60584639,  0.84729669,  0.34009085],
        [ 0.65268938, -1.74199645,  1.17156486],
        [-0.58347613,  1.18802306, -0.40484808],
        [ 0.42887053, -0.10296792,  0.17272983],
        [ 0.05724672, -0.45840373,  0.62510321]],

       [[-1.48787753, -1.8824463 , -0.52752826],
        [-0.35889936, -0.51439553, -0.39988129],
        [-0.75001131, -0.65893857, -0.25690081],
        [-0.50772625,  0.76472086, -0.69466651],
        [ 0.10473713, -1.40871525, -0.93874599]],

       [[-0.67693319,  0.27425455,  0.09212521],
        [ 0.57976008, -0.24645967,  3.79852131],
        [-0.62550056, -0.96741376,  1.0588209 ],
        [-0.69246371, -0.35042833,  0.02613722],
        [ 1.235935  ,  0.07780307,  0.39644594]],

       [[ 0.10152312,  0.31951816,  0.70087053],
        [-1.24601864, -0.42701681,  0.73233577],
        [-0.38392993,  1.72285966, -1.15549643],
        [-0.00744541, -0.32660382, -0.72501787],
        [ 0.47706213, -0.03557163, -0.27577264]],

       [[ 0.

9

In [3]:
import numpy as np
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.4328505340691283

array([[[ 0.32583901, -0.1814744 ,  1.03971954],
        [ 0.68860411,  0.21886586,  1.48391047],
        [-1.11585726, -0.4715048 , -0.71330103],
        [ 2.40506947, -0.78565298, -0.40840093],
        [ 2.76010746, -0.73437929, -0.11571749]],

       [[ 0.59248559, -0.18581118, -1.27485917],
        [-1.20595826,  1.53106661,  1.43267817],
        [-1.98415867, -0.3799047 , -0.74588892],
        [-1.63881011, -1.04130318, -0.85028428],
        [ 0.84965316, -0.3888579 , -0.8731854 ]],

       [[ 0.18476141, -0.03002689, -0.6186638 ],
        [-0.89403709, -1.11413745, -0.90498853],
        [-1.54859681,  0.07269079, -0.33255909],
        [ 0.68142686,  0.69564065,  0.94639248],
        [ 1.10315483, -0.7499989 ,  0.09592927]],

       [[-1.7265358 ,  0.17517237,  1.56319418],
        [ 0.52246214,  0.91299769, -0.01426926],
        [-0.49374589,  0.14084975, -0.19029296],
        [ 1.3998217 ,  1.02743243,  0.21278795],
        [-2.31030462,  0.4155147 ,  1.20409091]],

       [[ 0.

array([[7, 4, 9, 6, 6],
       [3, 9, 9, 1, 5],
       [1, 1, 1, 3, 2],
       [2, 4, 4, 3, 6],
       [4, 3, 3, 9, 5],
       [9, 3, 2, 3, 5],
       [1, 8, 4, 4, 2],
       [8, 5, 5, 2, 8],
       [8, 2, 5, 3, 8],
       [6, 9, 8, 6, 1]])